### ISSUE TITLE
Thesis Report & Presentation available on request, for an in-depth description of this project and any further information.

### ISSUE THREAD

**Issue by Cynthia-liang** [darraghmaguire/automatic-scoliosis-assessment#1]
Dear Darragh,

Could you please provide me the thesis report? Thank you very much!

Best,
Cynthia

**Comment by scoliosistools** [comment]
Hi Cynthia,

Thanks for your interest in the project!
Do you mind me asking the purpose of your request? Are you researching academically or in industry?

All the best,

Darragh

**Comment by Cynthia-liang** [comment]
Hi Darragh,

My purpose is academical. I am from Institute of Textile and Clothing, The Hong Kong Polytechnic University. Our group has been working on scoliosis in recent years and a flexible brace has been developed. Now, we hope to apply AI into our research and the first step is to learn this method to automatically measure the Cobb's angle.
 I really appreciate if you are willing to share more.

Best,
Cynthia

**Comment by scoliosistools** [comment]
Sounds great Cynthia! I'm happy to share the thesis with you for research purposes. If you could send me your email address, I'll send you on the report.

Darragh

**Comment by Cynthia-liang** [comment]
Thank you very much! My email is cynthia.rx.liang@connect.polyu.hk

Best,
Cynthia
