### ISSUE TITLE
Thesis Report & Presentation

### ISSUE THREAD

**Issue by zougougou** [darraghmaguire/automatic-scoliosis-assessment#2]
Hello, I'm studying scoliosis. I'm very interested in your project. Can you send me a report about this project? I'd like to know the evaluation of the experimental results you get.
My email is `zgg_run@outlook.com`, thank you very much

**Comment by scoliosistools** [comment]
Hi there, delighted to hear that you're interested in the project.
No problem at all, I can send on the report. I'll get in touch via email.
