### ISSUE TITLE
Query regarding MATLAB on Google Colab

### ISSUE THREAD

**Issue by jocelyntehsr** [darraghmaguire/automatic-scoliosis-assessment#3]
Hi, 

Thanks for the amazing codes!

May I ask, to run MATLAB, do we run it on Google Colab using octave? Or how should I run it? Thanks in advance.

**Comment by jocelyntehsr** [comment]
Also, may I obtain the thesis report and presentation? I am an engineering student from Malaysia who is keen to learn about AI, therefore it would help me a lot in understanding how deep learning can help in identifying scoliosis problem for research purpose! 

My email address is jocelynmg@hotmail.com 

Thanks in advance :)

**Comment by scoliosistools** [comment]
Hi Jocelyn! Great to hear that you're interested in the project, I'll send the full report to you email address now!

Regarding the MATLAB code, I ran those scripts using MATLAB that was installed locally on my machine, and only moved to Google Colab for the CNN training where I needed the GPUs.
All of the scripts in the 'dataset-preprocessing' folder should be run locally first. If you have google drive file stream set up then the 'createPickleDatasets.py' script will save to google drive where google Colab can easily access the data for the 'vertebra-segmentation-network' section. Then the final performance-evaluation scripts can be run locally also.
This explained in more detail in the README file, but let me know if anything isn't clear!
