### ISSUE TITLE
Dataset unavailable 

### ISSUE THREAD

**Issue by AbhiRishi96** [darraghmaguire/automatic-scoliosis-assessment#5]
I tried downloading the dataset from the link mentioned in Readme. Got 404 error.

**Comment by scoliosistools** [comment]
I've updated the link in the readme:
http://spineweb.digitalimaginggroup.ca/Index.php?n=Main.Datasets#Dataset_16.3A_609_spinal_anterior-posterior_x-ray_images

**Comment by yangbojiaer** [comment]
I tried downloading the dataset from the new url: http://spineweb.digitalimaginggroup.ca/Index.php?n=Main.Datasets#Dataset_16.3A_609_spinal_anterior-posterior_x-ray_images. But got HTTP ERROR 502.
Do you have the copy dataset at local? Can you share with me?

**Comment by yangbojiaer** [comment]
My email address is yangbojiaer@163.com, thank you very much!
